kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: login-service-deployment
  labels:
    app: login-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-service-app
  template:
    metadata:
      labels:
        app: login-service-app
    spec:
      containers:
      - name: login-service-app
        image: container-registry/service:latest
        ports:
           - containerPort: 4201
        resources:
         requests:
          cpu: "500m" # X/1000 of a CPU