kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: login-service
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-service
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50