kind: Service
apiVersion: v1
metadata:
  name: login-service-service
  labels:
    app: login-service-app
spec:
  type: ClusterIP
  selector:
    app: login-service-app
  ports:
  - name: http
    port: 80
    targetPort: 4201