kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: service
  labels:
    app: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: container-registry/service:latest
        resources:
         requests:
          cpu: "500m" # X/1000 of a CPU
---
kind: Service
apiVersion: v1
metadata:
  name: service
  labels:
    app: service
spec:
  type: LoadBalancer
  selector:
    app: service
  ports:
  - port: 80
    targetPort: 4201
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: service
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50