# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

spec:
  template:
    metadata:
    spec:
      initContainers:
      - image: acrmicroserviceswestus.azurecr.io/hexadite:latest 
        env:
        - value: https://microservices-deploy-kv.vault.azure.net 
